// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bgpPacket.proto

package in.netstack.netstacktool;

public final class BgpPacket {
  private BgpPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface bgpPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:in.netstack.netstacktool.bgpPacket)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 version = 1;</code>
     */
    int getVersion();
  }
  /**
   * Protobuf type {@code in.netstack.netstacktool.bgpPacket}
   */
  public  static final class bgpPacket extends
      com.google.protobuf.GeneratedMessageLite<
          bgpPacket, bgpPacket.Builder> implements
      // @@protoc_insertion_point(message_implements:in.netstack.netstacktool.bgpPacket)
      bgpPacketOrBuilder {
    private bgpPacket() {
    }
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>optional int32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }
    /**
     * <code>optional int32 version = 1;</code>
     */
    private void setVersion(int value) {
      
      version_ = value;
    }
    /**
     * <code>optional int32 version = 1;</code>
     */
    private void clearVersion() {
      
      version_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeInt32(1, version_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static in.netstack.netstacktool.BgpPacket.bgpPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static in.netstack.netstacktool.BgpPacket.bgpPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static in.netstack.netstacktool.BgpPacket.bgpPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static in.netstack.netstacktool.BgpPacket.bgpPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static in.netstack.netstacktool.BgpPacket.bgpPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static in.netstack.netstacktool.BgpPacket.bgpPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static in.netstack.netstacktool.BgpPacket.bgpPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static in.netstack.netstacktool.BgpPacket.bgpPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static in.netstack.netstacktool.BgpPacket.bgpPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static in.netstack.netstacktool.BgpPacket.bgpPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(in.netstack.netstacktool.BgpPacket.bgpPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code in.netstack.netstacktool.bgpPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          in.netstack.netstacktool.BgpPacket.bgpPacket, Builder> implements
        // @@protoc_insertion_point(builder_implements:in.netstack.netstacktool.bgpPacket)
        in.netstack.netstacktool.BgpPacket.bgpPacketOrBuilder {
      // Construct using in.netstack.netstacktool.BgpPacket.bgpPacket.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int32 version = 1;</code>
       */
      public int getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>optional int32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>optional int32 version = 1;</code>
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:in.netstack.netstacktool.bgpPacket)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new in.netstack.netstacktool.BgpPacket.bgpPacket();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          in.netstack.netstacktool.BgpPacket.bgpPacket other = (in.netstack.netstacktool.BgpPacket.bgpPacket) arg1;
          version_ = visitor.visitInt(version_ != 0, version_,
              other.version_ != 0, other.version_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  version_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (in.netstack.netstacktool.BgpPacket.bgpPacket.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:in.netstack.netstacktool.bgpPacket)
    private static final in.netstack.netstacktool.BgpPacket.bgpPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new bgpPacket();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static in.netstack.netstacktool.BgpPacket.bgpPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<bgpPacket> PARSER;

    public static com.google.protobuf.Parser<bgpPacket> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
